dist: xenial
language: python
stages:
  - syntax
  - test
jobs:
  include:
    - stage: syntax
      python: "3.6"
      install:
        - pip install -r requirements.txt flake8 black
      script:
        - flake8
        - black --check --diff .
    - stage: test
      python:
        - "3.4"
        - "3.5"
        - "3.6"
        - "3.7"
      install:
        - pip install -r requirements.txt tox-travis
        - tox
